steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/saas-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/saas-backend:latest'
      - './backend'
    id: 'build-backend-image'

  # Step 2: Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/saas-backend:$COMMIT_SHA'
    id: 'push-backend-image'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'saas-backend-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/saas-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'sa-backend-firebase@onborda.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,FIREBASE_PROJECT_ID=onborda,FIREBASE_CLIENT_EMAIL=sa-backend-firebase@onborda.iam.gserviceaccount.com,ALLOWED_ORIGINS=https://onborda.web.app,https://onborda.firebaseapp.com'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
    id: 'deploy-to-cloud-run'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/saas-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/saas-backend:latest'
